### ISSUE TITLE
[feature] 개발환경 구축

### ISSUE THREAD

**Issue by domino8788** [thebeeisfree/eyebee#2]
### 기능

- frontend-web의 개발환경을 구축한다.

### todo ✅

- [ ] react를 개발할 수 있는 환경을 구축한다.
- [ ] vite를 이용해 빌드할 수 있게 한다.
- [ ] 언어로 typescript를 사용하게 한다.
